// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type EndMeetingReq struct {
	UserId    uint64 `json:"-"` // 服务端填充，不在客户端 JSON 中
	MeetingId uint64 `json:"meetingId"`
}

type StartMeetingReq struct {
	UserId      uint64 `json:"-"` // 服务端填充，不在客户端 JSON 中
	MeetingId   uint64 `json:"meetingId"`
	MeetingName string `json:"meetingName"`
	JoinType    uint64 `json:"joinType"` // 0: 开放 1: 密码
	Password    string `json:"password"`
}
