// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type CaptchaReq struct {
	Email  string `json:"email"`
	Expire int64  `json:"expire"`
}

type PingReq struct {
	Msg string `json:"msg"`
}
