// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type LoginResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
	UserId int64  `json:"user_id"`
	Msg    string `json:"msg"`
}
