// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GetMeetingInfoResp struct {
	MeetingId   uint64 `json:"meetingId"`
	MeetingName string `json:"meetingName"`
	JoinType    uint64 `json:"joinType"`
	StartTime   int64  `json:"startTime"`
}

type GetMeetingMembersResp struct {
	Members []uint64 `json:"members"`
}

type LoginResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
	UserId int64  `json:"user_id"`
	Msg    string `json:"msg"`
}
