// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Captcha  string `json:"captcha"`
}
type LoginResp struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
	UserId int64  `json:"user_id"`
	Msg    string `json:"msg"`
}

type SignUpReq struct {
	Email    string `json:"email"`
	Username string `json:"username"`
	Password string `json:"password"`
	Captcha  string `json:"captcha"`
	Sex      int32  `json:"sex"`
	Avatar   string `json:"avatar"`
}
