// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendRequestsFieldNames          = builder.RawFieldNames(&FriendRequests{})
	friendRequestsRows                = strings.Join(friendRequestsFieldNames, ",")
	friendRequestsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendRequestsRowsWithPlaceHolder = strings.Join(stringx.Remove(friendRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendRequestsIdPrefix    = "cache:friendRequests:id:"
	cacheFriendRequestsReqIdPrefix = "cache:friendRequests:reqId:"
)

type (
	friendRequestsModel interface {
		Insert(ctx context.Context, data *FriendRequests) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*FriendRequests, error)
		FindOneByReqId(ctx context.Context, reqId uint64) (*FriendRequests, error)
		Update(ctx context.Context, data *FriendRequests) error
		Delete(ctx context.Context, id uint64) error

		FindRowsByFriendIndexAndHandleResult(ctx context.Context, friendIndex uint64, handleResult int64)(list []*FriendRequests, err error)

	}

	defaultFriendRequestsModel struct {
		sqlc.CachedConn
		table string
	}

	FriendRequests struct {
		Id           uint64         `db:"id"`            // 主键
		ReqId        uint64         `db:"req_id"`        // 好友请求ID
		UserIndex    uint64         `db:"user_index"`    // 用户主键
		FriendIndex  uint64         `db:"friend_index"`  // 好友主键
		ReqMsg       sql.NullString `db:"req_msg"`       // 申请信息
		ReqTime      time.Time      `db:"req_time"`      // 申请时间
		HandleResult int64          `db:"handle_result"` // 处理结果:0-待处理，1-同意，2-拒绝
		HandleMsg    sql.NullString `db:"handle_msg"`    // 处理信息
		HandleTime   sql.NullTime   `db:"handle_time"`   // 处理时间
	}
)

func newFriendRequestsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendRequestsModel {
	return &defaultFriendRequestsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friend_requests`",
	}
}

func (m *defaultFriendRequestsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, id)
	friendRequestsReqIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsReqIdPrefix, data.ReqId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendRequestsIdKey, friendRequestsReqIdKey)
	return err
}

func (m *defaultFriendRequestsModel) FindOne(ctx context.Context, id uint64) (*FriendRequests, error) {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, id)
	var resp FriendRequests
	err := m.QueryRowCtx(ctx, &resp, friendRequestsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRequestsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendRequestsModel) FindOneByReqId(ctx context.Context, reqId uint64) (*FriendRequests, error) {
	friendRequestsReqIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsReqIdPrefix, reqId)
	var resp FriendRequests
	err := m.QueryRowIndexCtx(ctx, &resp, friendRequestsReqIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `req_id` = ? limit 1", friendRequestsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, reqId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendRequestsModel) Insert(ctx context.Context, data *FriendRequests) (sql.Result, error) {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, data.Id)
	friendRequestsReqIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsReqIdPrefix, data.ReqId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, friendRequestsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ReqId, data.UserIndex, data.FriendIndex, data.ReqMsg, data.ReqTime, data.HandleResult, data.HandleMsg, data.HandleTime)
	}, friendRequestsIdKey, friendRequestsReqIdKey)
	return ret, err
}

func (m *defaultFriendRequestsModel) Update(ctx context.Context, newData *FriendRequests) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, data.Id)
	friendRequestsReqIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsReqIdPrefix, data.ReqId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendRequestsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.ReqId, newData.UserIndex, newData.FriendIndex, newData.ReqMsg, newData.ReqTime, newData.HandleResult, newData.HandleMsg, newData.HandleTime, newData.Id)
	}, friendRequestsIdKey, friendRequestsReqIdKey)
	return err
}

func (m *defaultFriendRequestsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, primary)
}

func (m *defaultFriendRequestsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRequestsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendRequestsModel) tableName() string {
	return m.table
}

func (m *defaultFriendRequestsModel) FindRowsByFriendIndexAndHandleResult(ctx context.Context, friendIndex uint64, handleResult int64)(list []*FriendRequests, err error){
	query := fmt.Sprintf("select %s from %s where `friend_index` = ? AND `handle_result` = ?", friendRequestsRows, m.table)
	err = m.QueryRowsNoCacheCtx(ctx,list,query,friendIndex,handleResult)
	return
}