// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.3

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendsFieldNames          = builder.RawFieldNames(&Friends{})
	friendsRows                = strings.Join(friendsFieldNames, ",")
	friendsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	friendsRowsWithPlaceHolder = strings.Join(stringx.Remove(friendsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendsIdPrefix                   = "cache:friends:id:"
	cacheFriendsUserIndexFriendIndexPrefix = "cache:friends:userIndex:friendIndex:"
)

type (
	friendsModel interface {
		Insert(ctx context.Context, data *Friends) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Friends, error)
		FindOneByUserIndexFriendIndex(ctx context.Context, userIndex uint64, friendIndex uint64) (*Friends, error)
		Update(ctx context.Context, data *Friends) error
		Delete(ctx context.Context, id uint64) error

		FindRowsByUserIndex(ctx context.Context, userIndex uint64)(list []*Friends, err error)
	}

	defaultFriendsModel struct {
		sqlc.CachedConn
		table string
	}

	Friends struct {
		Id          uint64         `db:"id"`           // 主键
		UserIndex   uint64         `db:"user_index"`   // 用户主键
		FriendIndex uint64         `db:"friend_index"` // 好友主键
		Comment     sql.NullString `db:"comment"`      // 好友备注
		CreateTime  time.Time      `db:"create_time"`  // 创建时间
		DeleteTime  sql.NullTime   `db:"delete_time"`  // 删除时间
	}
)

func newFriendsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendsModel {
	return &defaultFriendsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friends`",
	}
}

func (m *defaultFriendsModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, id)
	friendsUserIndexFriendIndexKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIndexFriendIndexPrefix, data.UserIndex, data.FriendIndex)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendsIdKey, friendsUserIndexFriendIndexKey)
	return err
}

func (m *defaultFriendsModel) FindOne(ctx context.Context, id uint64) (*Friends, error) {
	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, id)
	var resp Friends
	err := m.QueryRowCtx(ctx, &resp, friendsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendsModel) FindOneByUserIndexFriendIndex(ctx context.Context, userIndex uint64, friendIndex uint64) (*Friends, error) {
	friendsUserIndexFriendIndexKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIndexFriendIndexPrefix, userIndex, friendIndex)
	var resp Friends
	err := m.QueryRowIndexCtx(ctx, &resp, friendsUserIndexFriendIndexKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_index` = ? and `friend_index` = ? limit 1", friendsRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userIndex, friendIndex); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendsModel) Insert(ctx context.Context, data *Friends) (sql.Result, error) {
	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, data.Id)
	friendsUserIndexFriendIndexKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIndexFriendIndexPrefix, data.UserIndex, data.FriendIndex)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, friendsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserIndex, data.FriendIndex, data.Comment, data.DeleteTime)
	}, friendsIdKey, friendsUserIndexFriendIndexKey)
	return ret, err
}

func (m *defaultFriendsModel) Update(ctx context.Context, newData *Friends) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	friendsIdKey := fmt.Sprintf("%s%v", cacheFriendsIdPrefix, data.Id)
	friendsUserIndexFriendIndexKey := fmt.Sprintf("%s%v:%v", cacheFriendsUserIndexFriendIndexPrefix, data.UserIndex, data.FriendIndex)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserIndex, newData.FriendIndex, newData.Comment, newData.DeleteTime, newData.Id)
	}, friendsIdKey, friendsUserIndexFriendIndexKey)
	return err
}

func (m *defaultFriendsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheFriendsIdPrefix, primary)
}

func (m *defaultFriendsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendsModel) tableName() string {
	return m.table
}

func (m *defaultFriendsModel) FindRowsByUserIndex(ctx context.Context, userIndex uint64)(list []*Friends, err error){
	query := fmt.Sprintf("select %s from %s where `user_index` = ?", friendsRows, m.table)
	err = m.QueryRowsNoCacheCtx(ctx,list,query,userIndex)
	return
}