// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.7
// source: rpcs/meeting/rpc/meeting.proto

package meeting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_rpcs_meeting_rpc_meeting_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Result) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_rpcs_meeting_rpc_meeting_proto_rawDescGZIP(), []int{1}
}

func (x *PingReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateMeetingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    uint64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	MeetingId uint64 `protobuf:"varint,3,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
}

func (x *CreateMeetingReq) Reset() {
	*x = CreateMeetingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMeetingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingReq) ProtoMessage() {}

func (x *CreateMeetingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingReq.ProtoReflect.Descriptor instead.
func (*CreateMeetingReq) Descriptor() ([]byte, []int) {
	return file_rpcs_meeting_rpc_meeting_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMeetingReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateMeetingReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateMeetingReq) GetMeetingId() uint64 {
	if x != nil {
		return x.MeetingId
	}
	return 0
}

type StartMeetingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIndex   uint64 `protobuf:"varint,1,opt,name=userIndex,proto3" json:"userIndex,omitempty"`
	MeetingId   uint64 `protobuf:"varint,2,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	MeetingName string `protobuf:"bytes,3,opt,name=meetingName,proto3" json:"meetingName,omitempty"`
	JoinType    uint64 `protobuf:"varint,4,opt,name=joinType,proto3" json:"joinType,omitempty"`
	Password    string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *StartMeetingReq) Reset() {
	*x = StartMeetingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartMeetingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMeetingReq) ProtoMessage() {}

func (x *StartMeetingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMeetingReq.ProtoReflect.Descriptor instead.
func (*StartMeetingReq) Descriptor() ([]byte, []int) {
	return file_rpcs_meeting_rpc_meeting_proto_rawDescGZIP(), []int{3}
}

func (x *StartMeetingReq) GetUserIndex() uint64 {
	if x != nil {
		return x.UserIndex
	}
	return 0
}

func (x *StartMeetingReq) GetMeetingId() uint64 {
	if x != nil {
		return x.MeetingId
	}
	return 0
}

func (x *StartMeetingReq) GetMeetingName() string {
	if x != nil {
		return x.MeetingName
	}
	return ""
}

func (x *StartMeetingReq) GetJoinType() uint64 {
	if x != nil {
		return x.JoinType
	}
	return 0
}

func (x *StartMeetingReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type JoinMeetingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIndex uint64 `protobuf:"varint,1,opt,name=userIndex,proto3" json:"userIndex,omitempty"`
	MeetingId uint64 `protobuf:"varint,2,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	Password  string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *JoinMeetingReq) Reset() {
	*x = JoinMeetingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinMeetingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMeetingReq) ProtoMessage() {}

func (x *JoinMeetingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMeetingReq.ProtoReflect.Descriptor instead.
func (*JoinMeetingReq) Descriptor() ([]byte, []int) {
	return file_rpcs_meeting_rpc_meeting_proto_rawDescGZIP(), []int{4}
}

func (x *JoinMeetingReq) GetUserIndex() uint64 {
	if x != nil {
		return x.UserIndex
	}
	return 0
}

func (x *JoinMeetingReq) GetMeetingId() uint64 {
	if x != nil {
		return x.MeetingId
	}
	return 0
}

func (x *JoinMeetingReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EndMeetingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIndex uint64 `protobuf:"varint,1,opt,name=userIndex,proto3" json:"userIndex,omitempty"`
	MeetingId uint64 `protobuf:"varint,2,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
}

func (x *EndMeetingReq) Reset() {
	*x = EndMeetingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndMeetingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndMeetingReq) ProtoMessage() {}

func (x *EndMeetingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndMeetingReq.ProtoReflect.Descriptor instead.
func (*EndMeetingReq) Descriptor() ([]byte, []int) {
	return file_rpcs_meeting_rpc_meeting_proto_rawDescGZIP(), []int{5}
}

func (x *EndMeetingReq) GetUserIndex() uint64 {
	if x != nil {
		return x.UserIndex
	}
	return 0
}

func (x *EndMeetingReq) GetMeetingId() uint64 {
	if x != nil {
		return x.MeetingId
	}
	return 0
}

type AppointmentMeetingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MeetingId uint64 `protobuf:"varint,1,opt,name=meetingId,proto3" json:"meetingId,omitempty"`
	StartTime int64  `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"`
}

func (x *AppointmentMeetingReq) Reset() {
	*x = AppointmentMeetingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppointmentMeetingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentMeetingReq) ProtoMessage() {}

func (x *AppointmentMeetingReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpcs_meeting_rpc_meeting_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentMeetingReq.ProtoReflect.Descriptor instead.
func (*AppointmentMeetingReq) Descriptor() ([]byte, []int) {
	return file_rpcs_meeting_rpc_meeting_proto_rawDescGZIP(), []int{6}
}

func (x *AppointmentMeetingReq) GetMeetingId() uint64 {
	if x != nil {
		return x.MeetingId
	}
	return 0
}

func (x *AppointmentMeetingReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

var File_rpcs_meeting_rpc_meeting_proto protoreflect.FileDescriptor

var file_rpcs_meeting_rpc_meeting_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x72, 0x70, 0x63, 0x73, 0x2f, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x72,
	0x70, 0x63, 0x2f, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x2e, 0x0a, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x64, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0xa7, 0x01, 0x0a,
	0x0f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c,
	0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b,
	0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x68, 0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x4d, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x4b, 0x0a, 0x0d, 0x45, 0x6e, 0x64, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x49, 0x64, 0x22, 0x53, 0x0a,
	0x15, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x32, 0xe3, 0x02, 0x0a, 0x07, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x29,
	0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3b, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x6d, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71,
	0x1a, 0x0f, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x35, 0x0a, 0x0a, 0x45, 0x6e, 0x64, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x16, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6e, 0x64, 0x4d, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x45, 0x0a, 0x12, 0x41, 0x70, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1e,
	0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x41, 0x70, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f,
	0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x37, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e, 0x4d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x17,
	0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x4d, 0x65, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x6d, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpcs_meeting_rpc_meeting_proto_rawDescOnce sync.Once
	file_rpcs_meeting_rpc_meeting_proto_rawDescData = file_rpcs_meeting_rpc_meeting_proto_rawDesc
)

func file_rpcs_meeting_rpc_meeting_proto_rawDescGZIP() []byte {
	file_rpcs_meeting_rpc_meeting_proto_rawDescOnce.Do(func() {
		file_rpcs_meeting_rpc_meeting_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpcs_meeting_rpc_meeting_proto_rawDescData)
	})
	return file_rpcs_meeting_rpc_meeting_proto_rawDescData
}

var file_rpcs_meeting_rpc_meeting_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpcs_meeting_rpc_meeting_proto_goTypes = []interface{}{
	(*Result)(nil),                // 0: meeting.Result
	(*PingReq)(nil),               // 1: meeting.PingReq
	(*CreateMeetingReq)(nil),      // 2: meeting.CreateMeetingReq
	(*StartMeetingReq)(nil),       // 3: meeting.StartMeetingReq
	(*JoinMeetingReq)(nil),        // 4: meeting.JoinMeetingReq
	(*EndMeetingReq)(nil),         // 5: meeting.EndMeetingReq
	(*AppointmentMeetingReq)(nil), // 6: meeting.AppointmentMeetingReq
}
var file_rpcs_meeting_rpc_meeting_proto_depIdxs = []int32{
	1, // 0: meeting.Meeting.Ping:input_type -> meeting.PingReq
	2, // 1: meeting.Meeting.CreateMeeting:input_type -> meeting.CreateMeetingReq
	3, // 2: meeting.Meeting.StartMeeting:input_type -> meeting.StartMeetingReq
	5, // 3: meeting.Meeting.EndMeeting:input_type -> meeting.EndMeetingReq
	6, // 4: meeting.Meeting.AppointmentMeeting:input_type -> meeting.AppointmentMeetingReq
	4, // 5: meeting.Meeting.JoinMeeting:input_type -> meeting.JoinMeetingReq
	0, // 6: meeting.Meeting.Ping:output_type -> meeting.Result
	0, // 7: meeting.Meeting.CreateMeeting:output_type -> meeting.Result
	0, // 8: meeting.Meeting.StartMeeting:output_type -> meeting.Result
	0, // 9: meeting.Meeting.EndMeeting:output_type -> meeting.Result
	0, // 10: meeting.Meeting.AppointmentMeeting:output_type -> meeting.Result
	0, // 11: meeting.Meeting.JoinMeeting:output_type -> meeting.Result
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpcs_meeting_rpc_meeting_proto_init() }
func file_rpcs_meeting_rpc_meeting_proto_init() {
	if File_rpcs_meeting_rpc_meeting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpcs_meeting_rpc_meeting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_meeting_rpc_meeting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_meeting_rpc_meeting_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMeetingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_meeting_rpc_meeting_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartMeetingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_meeting_rpc_meeting_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinMeetingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_meeting_rpc_meeting_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndMeetingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpcs_meeting_rpc_meeting_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppointmentMeetingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpcs_meeting_rpc_meeting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcs_meeting_rpc_meeting_proto_goTypes,
		DependencyIndexes: file_rpcs_meeting_rpc_meeting_proto_depIdxs,
		MessageInfos:      file_rpcs_meeting_rpc_meeting_proto_msgTypes,
	}.Build()
	File_rpcs_meeting_rpc_meeting_proto = out.File
	file_rpcs_meeting_rpc_meeting_proto_rawDesc = nil
	file_rpcs_meeting_rpc_meeting_proto_goTypes = nil
	file_rpcs_meeting_rpc_meeting_proto_depIdxs = nil
}
